name: Build events

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  force_build:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/force-build')
    uses: ./.github/workflows/build.yaml
    secrets: inherit
